name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main

env:
  TUMBLR_API_KEY: ${{ secrets.TUMBLR_API_KEY }}
  TUMBLR_BLOG_ID: ${{ secrets.TUMBLR_BLOG_ID }}
  TUMBLR_API_ENDPOINT: ${{ secrets.TUMBLR_API_ENDPOINT }}
  PAGE_SUBTITLE: ${{ secrets.PAGE_SUBTITLE }}
  PAGE_LIMIT: ${{ secrets.PAGE_LIMIT }}
  EXT_ABOUT: ${{ secrets.EXT_ABOUT }}
  EXT_ARCHIVE: ${{ secrets.EXT_ARCHIVE }}
  EXT_CATEGORIES: ${{ secrets.EXT_CATEGORIES }}
  SITE_TITLE: ${{ secrets.SITE_TITLE }}
  META_OG_URL: ${{ secrets.META_OG_URL }}
  META_DESCRIPTION: ${{ secrets.META_DESCRIPTION }}
  META_OG_IMG: ${{ secrets.META_OG_IMG }}
  HOST_NAME: ${{ secrets.HOST_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22.12.0'

    - name: Change directory to amaoto
      run: cd front/app/amaoto

    - name: Install dependencies
      run: npm install
      working-directory: front/app/amaoto

    - name: Build project
      run: npm run generate
      working-directory: front/app/amaoto


    - name: Deploy to Netlify
      run: npx netlify-cli deploy --dir=.output/public --prod
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
